// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC19ZR2Dkmc-FVVNICESMpIimGdt0HoTyw',
    appId: '1:346007822005:android:0a9e5fcadda4e8d92568fc',
    messagingSenderId: '346007822005',
    projectId: 'cura-link',
    storageBucket: 'cura-link.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnIROtPZRyKuTi6aw3aHrqLz99_fZUj_c',
    appId: '1:346007822005:ios:08e85858578839a92568fc',
    messagingSenderId: '346007822005',
    projectId: 'cura-link',
    storageBucket: 'cura-link.firebasestorage.app',
    androidClientId:
        '346007822005-hrtuccsgo8ed0odsan3afjaui0ulrd07.apps.googleusercontent.com',
    iosClientId:
        '346007822005-ivup1g26oqerhtprmjs53q909tfgguct.apps.googleusercontent.com',
    iosBundleId: 'com.example.curaLink',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcBxQ9PnfjGn_nayqn9IMeVxhsIXsGpmg',
    appId: '1:346007822005:web:54ae254767296ff62568fc',
    messagingSenderId: '346007822005',
    projectId: 'cura-link',
    authDomain: 'cura-link.firebaseapp.com',
    storageBucket: 'cura-link.firebasestorage.app',
    measurementId: 'G-EN21KKSNNY',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnIROtPZRyKuTi6aw3aHrqLz99_fZUj_c',
    appId: '1:346007822005:ios:08e85858578839a92568fc',
    messagingSenderId: '346007822005',
    projectId: 'cura-link',
    storageBucket: 'cura-link.firebasestorage.app',
    androidClientId:
        '346007822005-hrtuccsgo8ed0odsan3afjaui0ulrd07.apps.googleusercontent.com',
    iosClientId:
        '346007822005-ivup1g26oqerhtprmjs53q909tfgguct.apps.googleusercontent.com',
    iosBundleId: 'com.example.curaLink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcBxQ9PnfjGn_nayqn9IMeVxhsIXsGpmg',
    appId: '1:346007822005:web:9c7b08c1e45052832568fc',
    messagingSenderId: '346007822005',
    projectId: 'cura-link',
    authDomain: 'cura-link.firebaseapp.com',
    storageBucket: 'cura-link.firebasestorage.app',
    measurementId: 'G-B99WZYJDLY',
  );
}
