// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOs - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgEEVlFp-SaEMpNRRj1wl8DVKUqQYMl5w',
    appId: '1:592986644024:android:adc5a7d812f403987310cd',
    messagingSenderId: '592986644024',
    projectId: 'cura-link-36b0c',
    storageBucket: 'cura-link-36b0c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0MUcP2IKRvLAkxWup0d4sswd5O8_qqH4',
    appId: '1:592986644024:ios:cd39fd32dc2f88327310cd',
    messagingSenderId: '592986644024',
    projectId: 'cura-link-36b0c',
    storageBucket: 'cura-link-36b0c.firebasestorage.app',
    iosBundleId: 'com.example.curaLink',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp2Og7CtTjsa61i3xwL7k-hMIn57D0uBs',
    appId: '1:592986644024:web:e8aa0a4ace4571cb7310cd',
    messagingSenderId: '592986644024',
    projectId: 'cura-link-36b0c',
    authDomain: 'cura-link-36b0c.firebaseapp.com',
    storageBucket: 'cura-link-36b0c.firebasestorage.app',
    measurementId: 'G-BNLEQVL5ZD',
  );

}